name = "aik"
license = "MIT"
#TODO licenselink = "//github.com/syui/hugo-theme-arch/blob/master/LICENSE.mdTODO"
description = "Theme inspired by archlinux website style."
#TODO homepage = "//github.com/syui/hugo-theme-arch"
tags = ["syntax highlighting", "maxthjax", "rss", "gallery", "widgets", "google analytics", "useful shortcodes", "responsive", "bootstrap", "font awesome", "archlinux", "hotkeys"]
features = ["syntax highlighting", "maxthjax", "rss", "gallery", "widgets", "google analytics", "useful shortcodes", "responsive", "bootstrap", "font awesome", "archlinux", "hotkeys"]
min_version = 0.15

[author]
  name = "kai"
  homepage = "//kai.dj/"

# If reference an existing theme
[original]
  name = "archlinux"
  homepage = "https://archlinux.org"
  repo = "https://github.com/archlinux/archweb"
